title: Grecia Alvarez 
email: greciazarella09@gmail.com
description: >-
 Portfolio of Grecia Zarella Alvarez Leyva – Business Analytics Student | Python Projects | AI & Trading | Sustainable Business

baseurl: "" 
url: "https://greciaalvarez.github.io"
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

author: Greciaalvarez

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author_profile: true

include:
  - _pages


