title: Grecia Alvarez 
email: greciazarella09@gmail.com
description: >-
 Portfolio of Grecia Zarella Alvarez Leyva – Business Analytics Student | Python Projects | AI & Trading | Sustainable Business

baseurl: "" 
url: "https://greciaalvarez.github.io"
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

author:
  name: Grecia Zarella Alvarez Leyva
  avatar: /assets/images/Photo_profile.jpg 
  bio: "Business Analytics"
  location: San Francisco, CA
  email: greciazarella09@gmail.com
  linkedin: "https://www.linkedin.com/in/greciaalvarez/"
  github: greciaalvarez

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author_profile: true

include:
  - _pages


