title: Grecia Alvarez 
email: greciazarella09@gmail.com
description: >-
 Portfolio of Grecia Zarella Alvarez Leyva – Business Analytics Student | Python Projects | AI & Trading | Sustainable Business

baseurl: "" 
url: "https://greciaalvarez.github.io"
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

author:
  name: Grecia Zarella Alvarez Leyva
  avatar: "assets/images/Photo profile.JPG"
  bio: "Business Analytics Student"
  location: San Francisco, CA
  email: greciazarella09@gmail.com
  linkedin: "https://www.linkedin.com/in/greciaalvarez/"
  phone: "+1-257-209-1773"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

include:
  - _pages


